# ✅ FIXED: Linux EDR Agent Configuration
# All issues resolved - database compatible

agent:
  name: 'EDR-Agent-Linux-Fixed'
  version: '2.1.0-Linux-Fixed'
  platform: 'linux'
  heartbeat_interval: 30
  event_batch_size: 50
  event_queue_size: 1000
  debug_mode: false

server:
  host: '192.168.20.85'
  port: 5000
  auth_token: 'edr_agent_auth_2024'
  timeout: 30
  max_retries: 3
  retry_delay: 5

collection:
  enabled: true
  collect_processes: true
  collect_files: true
  collect_network: true
  collect_authentication: true
  collect_system_events: true
  polling_interval: 3

linux_specific:
  monitor_proc_filesystem: true
  use_inotify: true
  monitor_systemd: true
  paths_to_monitor:
    - '/etc'
    - '/usr/bin'
    - '/home'
    - '/tmp'

logging:
  level: 'INFO'
  console_enabled: true
  log_directory: './logs'

performance:
  max_cpu_usage: 25
  max_memory_usage: 512
  auto_throttle: true